// Initial property values object for easy updating

module.exports = {
  'NCP:ProtocolVersion': '',
  'NCP:Version': '',
  'NCP:InterfaceType': '',
  'NCP:HardwareAddress': '',
  'NCP:CCAThreshold': '',
  'NCP:TXPower': '',
  'NCP:Region': '',
  'NCP:ModeID': '',
  'unicastchlist': '',
  'broadcastchlist': '',
  'asyncchlist': '',
  'chspacing': '',
  'ch0centerfreq': '',
  'Network:Panid': '',
  'bcdwellinterval': '',
  'ucdwellinterval': '',
  'bcinterval': '',
  'ucchfunction': '',
  'bcchfunction': '',
  'macfilterlist': '',
  'macfiltermode': '',
  'Interface:Up': '',
  'Stack:Up': '',
  'Network:NodeType': '',
  'Network:Name': '',
  'dodagroutedest': '',
  'dodagroute': '',
  'numconnected': '',
  'connecteddevices': '',
  'IPv6:AllAddresses': ''
}
